name = "telegram-cloudflare-bot"
type = "javascript"

account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true

[env.production]
route = ""
zone_id = ""

[vars]
TELEGRAM_BOT_TOKEN = "6844595438:AAH-XFWagXnoXZclSm36ICf_hcLO7m1ewDw"
